### ISSUE TITLE
1.x API appears to have changed, producing errors now

### ISSUE THREAD

**Issue by watou** [brettflorio/fox2chimp#1]
It appears that [this line](https://github.com/brettflorio/fox2chimp/blob/427b91b5816ad02c48628ca7f92f7280db705537/MailChimpUtils.php#L60) is no longer good enough because "already subscribed" is no longer in the error message text.  I changed the line like so:

```
  ($retval or $mc->errorCode == 214 or preg_match("/already subscribed/i", $mc->errorMessage)) or
```

to add a check for error code 214, which I *believe* means user is already subscribed.

**Comment by rijarobinson** [comment]
@watou Thanks so much for that. We've had another user experience this issue, so your feedback has already been helpful. We're making the change to the integration example code.

**Comment by brettflorio** [comment]
@watou This should be resolved by https://github.com/brettflorio/fox2chimp/pull/2
Let us know if that doesn't fix it for you.
